name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install arm-none-eabi
      run: sudo apt install gcc-arm-none-eabi
    - name: make
      run: |
        cd gd32_rdm_responder
        pwd
        make -f Makefile.GD32
 
      
